version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "aae-slots-for-discord"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1qtptc8e4i17t"
s3_prefix = "aae-slots-for-discord"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
