AWSTemplateFormatVersion: 2010-09-09
Description: >-
  aae-slots-for-discord

# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform:
- AWS::Serverless-2016-10-31

Parameters:

  DiscordWebhookUrl:
    Description: hoge
    Type: String

  LoftAppUsername:
    Description: hoge
    Type: String
    NoEcho: True

  LoftAppPassword:
    Description: hoge
    Type: String
    NoEcho: True

Resources:
  LoftAppSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${AWS::StackName}/LoftAppSecret'
      SecretString: !Sub |
        {
          "username": "${LoftAppUsername}",
          "password": "${LoftAppPassword}"
        }

  PuppeteerLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: aae-slots-puppeteer
      ContentUri: ./layers/puppeteer
      CompatibleRuntimes:
        - nodejs14.x
    Metadata:
      BuildMethod: nodejs14.x

  ScheduledEventLogger:
    Type: AWS::Serverless::Function
    Properties:
      Description: Check free slots for online ask an expert
      Runtime: nodejs14.x
      CodeUri: dst/
      Handler: index.handler
      Layers: 
        - !Ref PuppeteerLayer
      Environment:
        Variables:
          TZ: Asia/Tokyo
          DISCORD_WEBHOOK_URL: !Ref DiscordWebhookUrl
          LOFTAPP_SECRET_ARN: !Ref LoftAppSecret
      Events:
        ScheduledEvents:
          Type: Schedule
          Properties:
            Schedule: cron(0 0/8 * * ? *)
      MemorySize: 1024
      Timeout: 60
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action: secretsmanager:GetSecretValue
              Resource: !Ref LoftAppSecret
